### ISSUE TITLE
TOML Settings Issues

### ISSUE THREAD

**Issue by LeeThompson** [ersh1/BG3_NativeCameraTweaks#16]
In the toml file, a few options have "This is the default", I wish they all had that; I find the camera changes too drastic in the default toml but I'm not sure what settings I need to change to make it closer to "vanilla".    What would also be helpful would be if a "vanilla" toml was included.

For the most part, I'm using this for a photo mode until Larian finally adds it so I don't want combat or tactical cameras to change at all.   I just want to be able to do nice closeups of my character and party.

**Comment by ersh1** [comment]
Hey, the settings that don't have defaults listed are already set to vanilla values :)
