### ISSUE TITLE
HotFix4 mod is damaged

### ISSUE THREAD

**Issue by xiaochen-CN** [ersh1/BG3_NativeCameraTweaks#2]
![{@%PP7KLZD4H0~MN8I5%UUM](https://github.com/ersh1/BG3_NativeCameraTweaks/assets/62801004/1599c91e-7302-40d4-81fe-e08e9e5e7864)
![NGZN%CS$GUJSOK`O$%$S_)L](https://github.com/ersh1/BG3_NativeCameraTweaks/assets/62801004/6d019bc2-f8a7-4216-8687-e48b3be244ee)
This mod saved my CRPG experience and I really like it. But just now he was damaged by the official patch, which made me very sad.
Please!Please![cry]

**Comment by ersh1** [comment]
Fixed in 1.0.1
