### ISSUE TITLE
Patch 7 support

### ISSUE THREAD

**Issue by Foul-Tarnished** [ersh1/BG3_NativeCameraTweaks#22]
v4.1.1.5849914

**Comment by Margen67** [comment]
@ersh1 Not sure if this helps, but I think these are some of the patterns that fail. Left is patch 7.
GetCameraObject `FUN_141c6d280`:
![image](https://github.com/user-attachments/assets/ca1cff29-1967-4c84-8df0-04cba46d29a3)
SDLMouseYHookAddress `FUN_14051ec60`:
![image](https://github.com/user-attachments/assets/b67bb314-69d4-4751-867b-24942b026206)

**Comment by ersh1** [comment]
@Margen67 Oh hey I didn't see this lol. A few of the functions are straight up gone so I had to find other ways.
Update's out :)
