### ISSUE TITLE
Request: Hide cursor or wraparound screen edges

### ISSUE THREAD

**Issue by spikespaz** [ersh1/BG3_NativeCameraTweaks#4]
When using my mouse button 5 to rotate, rotation can stop when the cursor reaches the edge of the screen. I would like the cursor to be hidden, and have the rotation continue.

**Comment by Foul-Tarnished** [comment]
Pretty sure there's an ingame setting for the game to "caught" the mouse.

Otherwise you can do this with SpecialK, but only in DX11, so not great

**Comment by spikespaz** [comment]
I haven't tried that setting, for two reasons.

- I use borderless windowed, and do not want the cursor to be captured *unless* under circumstances such as rotation.
- That setting probably doesn't wrap around the edges of the screen, but is most likely to enable raw input events to eliminate pointer acceleration.

Again, I haven't tried. Maybe that setting doesn't do what I think it does.

**Comment by Ch4nKyy** [comment]
Ersh stated that he is not interested to implement this.
I will release it in BG3WASD next week.

**Comment by spikespaz** [comment]
> Ersh stated that he is not interested in implementing this.
> I will release it in BG3WASD next week.

Just be careful your mod doesn't become an all-in-one mess.

**Comment by Ch4nKyy** [comment]
Haha won't happen. I think it is an important feature for the WASD / Third-Person controls. And you will be able to disable it.

**Comment by ersh1** [comment]
As Ch4nKyy said, it will be a feature in WASD soon :)
