### ISSUE TITLE
Minimap rotation not always changing or stuttering

### ISSUE THREAD

**Issue by d3xMachina** [ersh1/BG3_NativeCameraTweaks#8]
I have the following issue (with the default configuration) :
First, enable the minimap rotation (minimap facing north option disabled in the game options).
Then, look at the floor or the sky and rotate the camera : the minimap will not rotate properly. With a bit less angle, the minimap will rotate but not smoothly.

I'm on the latest version of the game (Patch 1).

**Comment by ersh1** [comment]
Yeah that seems to happen with extreme pitch settings. Not planning to do anything about it, not worth the effort. It's a vanilla issue.

**Comment by d3xMachina** [comment]
I just wanted to note that the issue has been fixed with Patch 2 and the latest native camera build. It's smooth no matter the angle now!

**Comment by ersh1** [comment]
Oh neat, I actually did notice I couldn't reproduce it before replying to the issue, but I just assumed my pitch settings were lower than before. Cool!
